---
- name: Add Linux host to Centreon using CLAPI
  hosts: central

  tasks:
        - name: Authenticate with Centreon API
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a add -v '{{ lhost_name }};{{ lhost_name }};{{ ip_lclient }};OS-Linux-SNMP-Custom;central;'"
      register: add_host_result
      become: true

    - name: Add SNMP community
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a setparam -v '{{ lhost_name }};snmp_community;{{ snmp_community }}'"

    - name: Add SNMP verion
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a setparam -v '{{ lhost_name }};snmp_version;{{ snmp_version }}'"
