---
- name: Delete user and password file
  hosts: linux

  tasks:
    - name: Check if the user exists
      command: "id {{ username }}"
      register: user_exists
      ignore_errors: true

    - name: Delete user if it exists
      user:
        name: "{{ username }}"
        state: absent
      when: user_exists.rc == 0

    - name: Delete the password file
      file:
        path: "{{ pwd_file }}"
        state: absent
