---
- name: Delete user and password file
  hosts: linux

  tasks:
    - name: Check if the user exists
      command: "id {{ l_username }}"
      register: user_exists
      ignore_errors: true

    - name: Delete user if it exists
      user:
        name: "{{ l_username }}"
        state: absent
      when: user_exists.rc == 0

    - name: Create or update secrets.yml file
      ansible.builtin.template:
        src: "/root/empty_secrets.yml.j2"
        dest: "{{ secret_file }}"
      delegate_to: localhost
