---
- name: Create or update user with random password
  hosts: linux

  tasks:
    - name: Check if the user exists
      command: "id {{ username }}"
      register: user_exists
      ignore_errors: true

    - name: Generate a random password
      set_fact:
        random_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Create or update user
      user:
        name: "{{ username }}"
        password: "{{ random_password | password_hash('sha512') }}"
        state: present
        update_password: always

    - name: Save username and password to password.txt file
      blockinfile:
        path: "{{ pwd_file }}"
        block: |
          Username: {{ username }}
          Password: {{ random_password }}
