---
- name: Add Linux host to Centreon using CLAPI
  hosts: linux:windows

  tasks:
    - name: Check if host exists
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a getparam -v '{{ hostname }};snmp_version'"
      register: check_host_result
      ignore_errors: true

    - name: Authenticate with Centreon API
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a add -v '{{ hostname }};{{ hostname }};var=inventory_hostname;{{ template }};central;'"
      register: add_host_result
      when: check_host_result.rc != 0

    - name: Add SNMP community
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a setparam -v '{{ hostname }};snmp_community;{{ snmp_community }}'"
      when: check_host_result.rc != 0

    - name: Add SNMP verion
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a setparam -v '{{ hostname }};snmp_version;{{ snmp_version }}'"
      when: check_host_result.rc != 0

    - name: Apply Template
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a applytpl -v {{ hostname }}"
      when: check_host_result.rc != 0

    - name: Export Configuration
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -a applycfg -v central"
      when: check_host_result.rc != 0
