---
- name: Delete host in Centreon using CLAPI
  hosts: linux:windows
  gather_facts: yes

  tasks:
    - name: Delete monitored host
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a del -v {{ hostname }}"
      delegate_to: central

    - name: Export Configuration
      command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -a applycfg -v central"
      delegate_to: central
