---
- name: Undo SNMP Installation and configuration
  hosts: linux:windows
  gather_facts: yes

  tasks:
    - name: Uninstall SNMP packages if installed
      when: ansible_name in groups['linux']
      dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - net-snmp
        - net-snmp-utils

    - name: Remove SNMP configuration file if exists
      when: ansible_name in groups['linux']
      file:
        path: /etc/snmp/snmpd.conf
        state: absent

    - name: Uninstall SNMP
      when: ansible_name in groups['windows']
      win_feature:
        name: "{{ item }}"
        state: absent
      loop:
      - SNMP-Service
      - rsat-snmp
