---
- name: Delete user and password file
  hosts: linux:windows

  tasks:
    - name: Delete linux user
      when: ansible_name in groups['linux']
      user:
        name: "{{ username }}"
        state: absent

    - name: Delete windows user
      when: ansible_name in groups['windows']
      win_user:
        name: "{{ username }}"
        state: absent

    - name: Create or update secrets.yml file
      ansible.builtin.template:
        src: "{{ e_pattern_secret }}"
        dest: "{{ secret_file }}"
      delegate_to: localhost
