---
- name: Check if host exists
  command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a getparam -v '{{ item.hostname }};snmp_version'"
  register: check_host
  ignore_errors: true

- name: Delete monitored host
  command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -o HOST -a del -v {{ item.hostname }}"
  when: check_host.rc == 0

- name: Export Configuration
  command: "centreon -u {{ centreon_username }} -p {{ centreon_password }} -a applycfg -v central"
  when: check_host.rc == 0
