---
- name: Install SNMP on AlmaLinux
  hosts: linux

  tasks:
    - name: Check if SNMP is installed
      shell: "rpm -q net-snmp"
      register: snmp_status
      ignore_errors: true

    - name: Install SNMP packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - net-snmp
        - net-snmp-utils
      when: snmp_status.rc != 0

    - name: Generate SNMPd configuration file
      template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
      notify: Restart SNMP service

    - name: Start SNMP service
      service:
        name: snmpd
        state: started
        enabled: yes

  handlers:
    - name: Restart SNMP service
      service:
        name: snmpd
        state: restarted

---
- name: Installer et configurer SNMP sur une machine Windows
  hosts: windows
  gather_facts: no
  
  tasks:
    - name: Installer SNMP Feature
      win_feature:
        name: SNMP-Service
        state: present

    - name: Copier le fichier de configuration SNMP
      win_template:
        src: w_snmpd.conf.j2
        dest: C:\Windows\System32\snmp\snmpd.conf

    - name: Redémarrer le service SNMP
      win_service:
        name: snmp
        state: restarted
