---
- name: Install SNMP on AlmaLinux
  hosts: linux

  tasks:
    - name: Check if SNMP is installed
      shell: "rpm -q net-snmp"
      register: snmp_status
      ignore_errors: true

    - name: Install SNMP packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - net-snmp
        - net-snmp-utils
      when: snmp_status.rc != 0

    - name: Generate SNMPd configuration file
      template:
        src: l_snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
      notify: Restart SNMP service

    - name: Start SNMP service
      service:
        name: snmpd
        state: started
        enabled: yes

  handlers:
    - name: Restart SNMP service
      service:
        name: snmpd
        state: restarted

- name: Installer et configurer SNMP sur une machine Windows
  hosts: windows
  gather_facts: no

  tasks:
    - name: Check if SNMP exist
      win_reg_stat:
        path: HKLM:\SYSTEM\CurrentConstrolSet\Services\SNMP
      register: snmp_reg_stat

    - name: Install SNMP
      win_feature:
        name: SNMP-Service
        state: present
      when: not snmp_reg_stat.exists

    - name: Install SNMP Feature
      ansible.windows.win_powershell:
        script: "Install-WindowsFeature rsat-snmp"

    - name: Configure SNMP
      win_snmp:
        community_strings:
          - public
        permitted_managers:
          - 192.168.1.2
        action: set

    - name: Restart service SNMP
      win_service:
        name: snmp
        state: restarted
