---
- name: Manage users on Linux and Windows
  hosts: linux:windows
  gather_facts: yes

  tasks:
    - name: Generate a random password
      set_fact:
        random_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Create or update Linux user
      when: ansible_host in groups['linux']
      user:
        name: "{{ username }}"
        password: "{{ random_password | password_hash('sha512') }}"
        state: present
        update_password: always

    - name: Create or update Windows user
      when: ansible_host in groups['windows']
      win_user:
        name: "{{ username }}"
        password: "{{ random_password | password_hash('sha512') }}"
        state: present
        update_password: always

    - name: Decrypt vault file
      delegate_to: localhost
      command: "bash /root/create_vault.sh -d"

    - name: Create or update secrets.yml file
      delegate_to: localhost
      lineinfile:
        dest: "{{ secret_file }}"
        regexp: "^{{ ansible_name }};"
        line: "{{ ansible_name }};{{ username }};{{ random_password }}"
        state: present

    - name: Encrypt vault file
      delegate_to: localhost
      command: "bash /root/create_vault.sh -e"
